### ISSUE TITLE
Unable to use save changes to module setting

### ISSUE THREAD

**Issue by simulacrum-1** [mclemente/about-face#7] opened 2021-09-30 09:00 UTC
Since the update I'm unable to save module settings.
If I uninstall about-face it works again.

**Comment by mclemente** [comment] 2021-09-30 12:41
I couldn't reproduce that. Does it throw any errors on the console?

**Comment by simulacrum-1** [comment] 2021-09-30 13:49
No. I don’t think so. I’ll run conflict finder tonight.

**Comment by simulacrum-1** [comment] 2021-09-30 14:13
This is the error

Mark

Mark Haylock Ltd
t: 07968 712049
e: ***@***.*** ***@***.***>

www.markhaylock.com <http://www.markhaylock.com/>

**Comment by simulacrum-1** [comment] 2021-09-30 14:22
I deactivated everything but about face and it works. It’s a conflict I think.

**Comment by simulacrum-1** [comment] 2021-09-30 14:25
![Screenshot 2021-09-30 at 15 24 27](https://user-images.githubusercontent.com/68729767/135473929-7fd02651-ea33-474c-b265-b584d2048e91.jpg)
A conflict this is the error when I try to save

**Comment by simulacrum-1** [comment] 2021-09-30 14:32
![Screenshot 2021-09-30 at 15 31 02](https://user-images.githubusercontent.com/68729767/135475275-bf3b5615-f507-4434-b379-d2adb0c0bf2e.jpg)

**Comment by simulacrum-1** [comment] 2021-09-30 14:32
It conflicts with Libwrapper

**Comment by mclemente** [comment] 2021-09-30 16:47
So that's why I couldn't replicate it, I didn't test it on scenes without tokens 🤦
I'll get it fixed in a bit. Thank you for reporting it.

**Comment by simulacrum-1** [comment] 2021-09-30 16:51
No problem. Thanks for fixing it so fast.

**Closed** 2021-09-30 20:37 UTC

**Comment by simulacrum-1** [comment] 2021-10-02 10:54
Thanks
